name: Release @rafat97/exceptionHandler typescript package

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  deploy-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2

      - name: Install yarn
        run: npm install -g yarn

      - name: Lerna version
        run: yarn lerna version --yes

      - name: Change directory to src/exceptionHandler
        run: cd src/exceptionHandler

      - name: Install dependencies
        run: yarn install

      - name: Publish package
        run: yarn run publish:npm



