name: Publish @rafat97/exceptionHandler typescript package

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  deploy-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2

      - name: Package.json package version patch
        run: |
            cd packages/exceptionHandler
            pwd
            npm run version:patch

      - name: Publish package
        run: npm run publish:npm

      - name: Git version & config
        run: |
            echo "Git version"
            git --version
            echo "Set config"
            git config --local user.email "rafathaque.bot@gmail.com"
            git config --local user.name  "rafat97bot"
            echo "Git config"
            git config --list

      - name: Commit package version
        run: |
            git status
            git add .
            git status
            git commit -m "🤖 AiS_Packages repo Update by ${{ github.actor }}"
            git push

